[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

[production]
hkare-prod-1 ansible_host=192.168.1.100
hkare-prod-2 ansible_host=192.168.1.101

[production:vars]
environment=production
docker_hub_username=umesh404
mysql_root_password=Umesh@05
mysql_password=Umesh@05
mysql_database=hkare

[staging]
hkare-staging-1 ansible_host=192.168.1.200

[staging:vars]
environment=staging
docker_hub_username=umesh404
mysql_root_password=Umesh@05
mysql_password=Umesh@05
mysql_database=hkare

[local]
localhost ansible_connection=local

[local:vars]
environment=local
docker_hub_username=umesh404
mysql_root_password=Umesh@05
mysql_password=Umesh@05
mysql_database=hkare

